- name: Install Gitlab
  apt:
    name: gitlab-ce
    state: present

- name: Configurer Gitlab
  template:
    src: gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb

- name: Reconfigure Gitlab
  command: gitlab-ctl reconfigure

- name: Pull Gitlab Docker image
  docker_image:
    name: gitlab/gitlab-ce
    tag: latest
    source: pull

- name: Install required system dependencies for psycopg2
  apt: 
     name: 
       - python3
       - python3-pip
       - libpq-dev
       - python3-dev
     state: present
