---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install required packages for Docker
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
    state: present

- name: Add Gitlab GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Install Docker CE
  apt:
    name: docker-ce
    state: present
  become: true

- name: Ensure Docker is running
  service:
    name: docker
    state: started
    enabled: true

- name: Install DockerCompose
  shell: |
    curl -L "https://github.com/docker/compose/releases/download/1.28.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    chmod +x /usr/local/bin/docker-compose
  args:
     creates: /usr/local/bin/docker-compose

- name: Add Gitlab repository
  copy:
    content: |
       deb [signed-by=/usr/share/keyrings/gitlab-archive-keyring.gpg] https://packages.gitlab.com/gitlab/gitlab-ce/ubuntu/ {{ ansible_distribution_release }} main
    dest: /etc/apt/sources.list.d/gitlab_gitlab.ce.list

- name: Update apt cache after adding Gitlab repository
  apt:
    update_cache: yes
